//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpps.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentToken
    {
        public int PaymentTokenID { get; set; }
        public int ProviderID { get; set; }
        public string ProviderToken { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
