//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpps.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderType
    {
        public ProviderType()
        {
            this.Providers = new HashSet<Provider>();
        }
    
        public int ProviderTypeID { get; set; }
        public string ProviderTypeName { get; set; }
    
        public virtual ICollection<Provider> Providers { get; set; }
    }
}
